services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: clean_city_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./api  
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
    working_dir: /app
    command: node server.js
    depends_on:
      - db
    env_file:
      - ./api/.env     # ✅ อยู่ภายใน backend service

volumes:
  db_data:
